# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# The docs are generated by running:
# .\make html
# from the folder docs/

# If some attempt has been tried before, first remove the folder source/_autosummary/
# and run:
# .\make clean

# add the directory containing the code to sys.path, so that Sphinx can import any module that must be documented
import sys, os
from pathlib import Path
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "src_code"))

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'AI from scratch'
copyright = '2025, Didier'
author = 'Didier'
release = '0.0.1'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# extensions = [
#     'sphinx.ext.autodoc',
#     'sphinx.ext.napoleon',
#     'sphinx.ext.todo',
#     'sphinx.ext.autosummary'
# ]
extensions = [
	"sphinx.ext.autosummary",  # Create neat summary tables for modules/classes/methods etc
	"sphinx.ext.intersphinx",  # Link to other project's documentation (see mapping below)
	"sphinx_autodoc_typehints",  # Automatically document param types (less noise in class signature)
	'sphinx.ext.napoleon',
	'sphinx.ext.autodoc',
    'sphinx_wagtail_theme'
]

# generate summaries automatically
autosummary_generate = True

# the objects appear in the documentation in the same order as in the code
autodoc_member_order = 'bysource'

# do not include the torch documentation in ours
autodoc_mock_imports = ['torch', 'torchvision', 'diffusers']

templates_path = ['_templates']
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# THIS is THE THEME!
html_theme = "sphinx_wagtail_theme"
html_static_path = ['_static']
